### ISSUE TITLE
events endpoint not working as expected

### ISSUE THREAD

**Issue by dcflachs** [titpetric/docker-proxy-acl#3]
Let me preface this by explaining that the changes I have submitted recently are aimed at getting this proxy to work with traefik. Though a programmer by trade I am a novice when it comes to go, and web technologies in general.
That said the events endpoint that i enabled recently is not working the way I expected it to and i could use the opinion of someone with more experience. My best guess so far is that it has to do with the fact that events returns a continuous stream of events rather than a single response. Does that sound like I might be on the right track? Additionally I found [this ](https://stackoverflow.com/questions/48691735/using-gorilla-mux-endpoint-to-stream-data-via-http) stackoverflow question which i think is imminently relevant. I am not sure however where this could be applied in the structure of docker proxy acl.

**Comment by titpetric** [comment]
Yes, most likely there's some sort of websocket handshake required for something like that. Using https://github.com/gorilla/websocket should be the first step, but I don't know if that websocket lib also works as a websocket client. Perhaps https://github.com/koding/websocketproxy should be a better bet to start with a reverse proxy impl for websocket.

**Comment by titpetric** [comment]
PR merged, sorry for the long turn around.
